name: HTTP triggered workflow

on:
  push:
    branches: [ main, master ]  # 当推送到主分支时触发
  pull_request:
    branches: [ main, master ]  # 当创建PR时触发
  workflow_dispatch:   

permissions:
  pull-requests: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: 18
      - run: npm i
      - run: npm run build
      - run: npm run test
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: ".dist/**/*.{js,ts,json}"
  # 其他 jobs 保持不变...
